# Basic Setting

### Library

In [67]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

### Random State

In [68]:
SEED = 42

# Data Collection

### Get data from url

In [69]:
data_url = 'https://raw.githubusercontent.com/20161609/data_box/refs/heads/main/penguins.csv'
df = pd.read_csv(data_url)
df.shape

(344, 7)

In [70]:
df.head()

,Species,Island,Culmen Length(mm),Culmen Depth(mm),Flipper Length(mm),Body Mass(g),Sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE

### Column name processing

In [71]:
def clean_column_names(col):
  # Change to lowercase and remove spaces and special characters ('_', '(', ')')
  col = col.strip()
  col = col.lower()
  col = col.replace(' ', '_')
  col = col.replace('(', '')
  col = col.replace(')', '')
  return col

df.columns = [clean_column_names(col) for col in df.columns]
df.head()

,species,island,culmen_lengthmm,culmen_depthmm,flipper_lengthmm,body_massg,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   species           344 non-null    object
 1   island            344 non-null    object
 2   culmen_lengthmm   342 non-null    float64
 3   culmen_depthmm    342 non-null    float64
 4   flipper_lengthmm  342 non-null    float64
 5   body_massg        342 non-null    float64
 6   sex               334 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

# Data Proprecessing

### Missing values

In [73]:
# Handle missing values in numeric columns by filling with mean
numeric_cols = df.select_dtypes(include=['number']).columns
for col in numeric_cols:
    if df[col].isnull().sum() > 0:
        print(f"Filling missing values in numeric column '{col}' with mean.")
        df[col].fillna(df[col].mean(), inplace=True)

# Handle missing values in categorical columns by filling with mode
categorical_cols = df.select_dtypes(include=['object', 'category']).columns
for col in categorical_cols:
    if df[col].isnull().sum() > 0:
        print(f"Filling missing values in categorical column '{col}' with mode.")
        df[col].fillna(df[col].mode()[0], inplace=True)

Filling missing values in numeric column 'culmen_lengthmm' with mean.
Filling missing values in numeric column 'culmen_depthmm' with mean.
Filling missing values in numeric column 'flipper_lengthmm' with mean.
Filling missing values in numeric column 'body_massg' with mean.
Filling missing values in categorical column 'sex' with mode.

<ipython-input-73-42b611614a1c>:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(), inplace=True)
<ipython-input-73-42b611614a1c>:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

### Encode categorical variables

In [74]:
# Convert categorical columns to numerical using Label Encoding
for col in categorical_cols:
  print(f"Encoding categorical column '{col}'.")

  le = LabelEncoder()
  # Convert to string before encoding
  df[col] = le.fit_transform(df[col].astype(str))

print("Missing values after preprocessing:")
print(df.isnull().sum())

Encoding categorical column 'species'.
Encoding categorical column 'island'.
Encoding categorical column 'sex'.
Missing values after preprocessing:
species             0
island              0
culmen_lengthmm     0
culmen_depthmm      0
flipper_lengthmm    0
body_massg          0
sex                 0
dtype: int64

### Duplication

In [75]:
initial_rows = df.shape[0]
df.drop_duplicates(inplace=True)
final_rows = df.shape[0]
print(f"Removed {initial_rows - final_rows} duplicate rows.")

Removed 0 duplicate rows.

# Data Preparation